version: '3.9'

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880"     # HTTP/WebSocket port
      - "7881:7881"     # TURN/UDP port
      - "7882:7882/udp" # RTC/UDP port
      - "50000-50100:50000-50100/udp" # RTC port range
    volumes:
      - ./livekit-config.yaml:/livekit.yaml
    command: --config /livekit.yaml --node-ip=0.0.0.0
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge
