port: 7880

# RTC Configuration
rtc:
  # UDP ports for WebRTC traffic
  port_range_start: 50000
  port_range_end: 50100
  # Use external IP for production, localhost for development
  use_external_ip: false
  # Allow localhost connections
  tcp_port: 7881

# Redis configuration (optional, for scalability)
# redis:
#   address: localhost:6379

# Room settings
room:
  # Auto create rooms
  auto_create: true
  # Empty timeout
  empty_timeout: 300 # 5 minutes
  # Max participants per room
  max_participants: 100

# API Keys
keys:
  # Format: api_key: api_secret
  devkey: this_is_a_very_secure_secret_key_with_at_least_32_characters_long
  # You can add more keys here
  # APIxxxxxxxxx: your_secret_here

# Logging
logging:
  level: info
  # Use 'debug' for more verbose logging during development
  # level: debug

# Turn server (for NAT traversal)
turn:
  enabled: true
  # Use embedded TURN server
  domain: localhost
  # TLS not required for local development
  tls_port: 0
  udp_port: 7882

# Webhook (optional, for events)
# webhook:
#   api_key: <webhook-key>
#   urls:
#     - http://localhost:5000/api/livekit-webhook

# CORS settings for web clients
# cors:
#   allow_origins:
#     - "*"
